version: 1.0.{build}
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
build:
  project: Source\PersistentMemoryCache.sln
  publish_nuget: true
  verbosity: minimal